PATCH http://localhost:3000/posts
Content-Type: application/json

{
  "id": 20,
  "title": "Hello, World Secondd!",
  "postType": "post",
  // "slug": "hello-world",
  "status": "draft",
  "content": "This is my first post.",
  "schema": "{\n  \"context\": \"https://schema.org\",\n  \"type\": \"person\"\n}",
  "featuredImageUrl": "http://localhost.com/image1",
  "publishOn": "2025-12-31T23:59:59",
  "tags": [1, 3],
  "metaOptions" : {
    "metaValue": "{ \"sidebarEnabled\": true, \"footerActive\": true }"
  }
}